# Generated by Django 4.1.5 on 2023-01-04 07:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=252, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image_url', models.URLField(blank=True, max_length=512, null=True)),
                ('source', models.URLField(blank=True, max_length=512, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('tag', models.ManyToManyField(related_name='tags', to='news.tag')),
            ],
        ),
    ]
