"""
Django settings for labglo_site project.

Generated by 'django-admin startproject' using Django 4.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@m(&@3@za4*6**^1e5bb9rybx(l_)3_n^x_6uf_z=t%^mmm_)p'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

        # Project apps
    'core',
    'career',
    'news',
    'blog',
        # Third party apps
    'crispy_forms',
    'djrichtextfield',
    'ckeditor',
    'ckeditor_uploader'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'labglo_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.recaptcha',
                'core.context_processors.latest_news_post',
                'core.context_processors.news_tag_list',
                'core.context_processors.latest_blog_post',
                'core.context_processors.blog_tag_list',
            ],
        },
    },
]

WSGI_APPLICATION = 'labglo_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'labglo',
        'USER': 'root',
        'PASSWORD': 'password',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

MAX_UPLOAD_SIZE = 10485760

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = '/opt/projects/labglo.com/labglo_static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = '/opt/projects/labglo.com/labglo_media/'


STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "static"),
    # '/var/www/static/',
)


# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field
EMAIL_USE_SSL = True
EMAIL_HOST = 'md-in-37.webhostbox.net'
EMAIL_PORT = 465
EMAIL_HOST_USER = "greetings@labglo.com"
SERVER_EMAIL = "greetings@labglo.com"
EMAIL_HOST_PASSWORD = "x[UVA9PDCbOP"
DEFAULT_FROM_EMAIL = "LabGlo Technologies LLP <greetings@labglo.com>"

RECAPTCHA_PUBLIC_KEY = '6LcNGBMUAAAAAOFyFyWCDtbbivl5jLTM62sC8AsM'
RECAPTCHA_PRIVATE_KEY = '6LcNGBMUAAAAAKzLPhMVFyv8IvC93q9Un122z5w9'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Django CkEditor settings
DJRICHTEXTFIELD_CONFIG = {
    'js': ['//tinymce.cachefly.net/4.1/tinymce.min.js'],
    'init_template': 'djrichtextfield/init/tinymce.js',
    'settings': {
        'menubar': False,
        'plugins': 'link image',
        'toolbar': 'bold italic | link image | removeformat',
        'width': 700
    }
}

CKEDITOR_UPLOAD_PATH = "uploads/"
CKEDITOR_IMAGE_BACKEND = "pillow"
CKEDITOR_RESTRICT_BY_USER = True
CKEDITOR_JQUERY_URL = '//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js'

# CKEDITOR_CONFIGS = {
#     'default': {
#         'toolbar': 'Advanced',
#         'width': 1000,
#         'height': 500,
#         'uiColor' : '#9ccde5',
#         'extraPlugins': ','.join(
#             [
#                 'syntaxhighlight',
#             ]),
#     },
# }

# Diffbot Product Crawl Developer Token
DEVELOPER_TOKEN = "a861b8cee5a3ce86c5e6a1692138fcc4"

try:
    from settings import *
except ImportError:
    pass

import logging

logging.basicConfig (
    level = logging.INFO,
    format = '%(asctime)s %(levelname)s %(message)s',
    filename = '/tmp/labgloLog.log',
)