# Generated by Django 4.1.5 on 2023-01-04 07:59

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=252)),
                ('last_name', models.CharField(max_length=252)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=0)),
                ('current_company', models.CharField(blank=True, max_length=125, null=True)),
                ('current_location', models.CharField(blank=True, max_length=125, null=True)),
                ('total_exp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('relevant_exp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('current_ctc', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_ctc', models.PositiveIntegerField(blank=True, null=True)),
                ('resume', models.FileField(upload_to='candidate_resumes')),
                ('notice_period', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('is_notified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Drive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('slug', models.SlugField(max_length=512, unique=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('from_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('to_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(blank=True, max_length=128, null=True)),
                ('last_date_to_apply', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DriveRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=252)),
                ('last_name', models.CharField(max_length=252)),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('qualification', models.CharField(max_length=256)),
                ('course', models.CharField(max_length=256)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('grade', models.CharField(blank=True, max_length=2, null=True)),
                ('college', models.CharField(max_length=512)),
                ('university', models.CharField(max_length=512)),
                ('location', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.CharField(blank=True, max_length=512, null=True)),
                ('state', models.CharField(blank=True, max_length=512, null=True)),
                ('referred_by', models.CharField(blank=True, max_length=512, null=True)),
                ('address', models.TextField(blank=True, max_length=512, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.drive')),
            ],
            options={
                'ordering': ('created_on', 'id'),
                'unique_together': {('email', 'drive')},
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=252)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('job_code', models.CharField(max_length=10, unique=True)),
                ('job_title', models.CharField(max_length=254)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('job_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('required_qualification', models.CharField(blank=True, max_length=254, null=True)),
                ('is_fresher', models.BooleanField(default=False)),
                ('min_exp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_exp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=125, null=True)),
                ('posting_date', models.DateTimeField(blank=True, null=True)),
                ('closing_date', models.DateTimeField(blank=True, null=True)),
                ('reference_link', models.URLField(blank=True, max_length=512, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('skills', models.ManyToManyField(related_name='required_skills', to='career.skill')),
            ],
        ),
        migrations.CreateModel(
            name='DriveTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.DateTimeField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('drive_registration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='career.driveregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to='career.candidate')),
                ('job_listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_listing', to='career.joblisting')),
            ],
        ),
        migrations.CreateModel(
            name='TempCandidate',
            fields=[
                ('candidate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='career.candidate')),
                ('verification_key', models.UUIDField(db_index=True, unique=True)),
                ('job_listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.joblisting')),
            ],
            bases=('career.candidate',),
        ),
    ]
