# Generated by Django 4.1.5 on 2023-01-04 10:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drive',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
